### ISSUE TITLE
Function to calculate how many percentage of looking and not looking

### ISSUE THREAD

**Issue by ihgumilar** [ihgumilar/Hyperscanning2-redesign#44]
**Do the following steps**

- [ ] - [ ] Call  this function for every pair instead of all pairs that have been combined
- [x] The result is a list that contains whether look at or not  throughout the experiment
- [x] Calculate the percentage of looking and not looking ,i.e. `(number of looking / len(total_looking_not_looking)) * 100`  for each pair **(return value of the function)**
